admin_id:
admin_room_id:
gpt_room_list:
gpt_sk:
gpt_user_list:
keyword_list:
- 刷选项
- 刷机包
- 日本
- fuck
- 举牌
- 刷机
keyword_room_list:
list_revoke:
morning_report_room_list:
random_list:
- '[旺柴]'
- '[发抖]'
- '[猪头]'
- 干啥？
- '[炸弹]'
- at我干啥，我只是一个没有感情的机器人，我又听不懂你说什么，哦对了，顺便说一句，不知名网友好帅
room_list:
user_list:
wxid_self:
gpt_flag: True